
# Anything that goes in etc/imw_site_config.yaml can go here, with the values
# here overriding those.  You may, for example, wish to tell your version
# control system to ignore this file and move the schemadb: section (or just its
# passwords) into here.
# imw_config:
#     config:   site # leave this in
    
    # Same configuration as the openrecord gem in Rails -- see docs there.
    # schemadb:
    #     adapter: sqlite3
    #     database: db/schemadb.sqlite3
    #     timeout: 5000
